language: C++
sudo: enabled
os: linux
dist: focal

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - mkdir build && cd build
 - cmake .. && cmake --build .
